exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "lib/tasks/*.rake"
- "app/assets/stylesheets/metronic/"
- "app/javascript/metronic/"
- "app/javascript/emojis/"

plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  reek:
    enabled: true
  scss-lint:
    enabled: true
