require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
