version: 2.1

executors:
  default:
    working_directory: ~/chattrful
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: chattrful
      - image: circleci/postgres:12.0
        environment:
          POSTGRES_DB: chattrful_test
          POSTGRES_USER: chattrful
          POSTGRES_PASSWORD: ""

commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            yarn global add sass
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            yarn
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache:
          paths:
            - ./vendor/bundle
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run:
          name: Setup DB
          command: bundle exec rails db:create
          # command: bundle exec rake db:schema:load

      - restore_cache:
          keys:
            - v1-asset-cache-{{ arch }}-{{ .Branch }}
            - v1-asset-cache-

      - run: bundle exec rake assets:precompile

      - save_cache:
          key: v1-asset-cache-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - public/assets
            - tmp/cache/assets/sprockets

      - run:
          name: RSpec
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec --profile 10 \
                              --format progress
            ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      - store_artifacts:
          path: coverage
      - save_cache:
          key: chattrful_postgresql-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/
          paths:
            - ./chattrful

  standardrb:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: StandardRb
          command: |
            gem install standardrb
            standardrb
  brakeman:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Brakeman
          command: |
            gem install brakeman
            brakeman

  fasterer:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Fasterer
          command: |
            gem install fasterer
            fasterer

  rails_best_practices:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Rails Best Practices
          command: |
            gem install rails_best_practices
            rails_best_practices

workflows:
  version: 2
  integration:
    jobs:
      - build
      - standardrb:
          requires:
            - build
      - brakeman:
          requires:
            - build
      - fasterer:
          requires:
            - build
      - rails_best_practices:
          requires:
            - build
