export default {
  emojis: [
    { name: 'See-No-Evil Monkey', emoji: '🙈' },
    { name: 'Hear-No-Evil Monkey', emoji: '🙉' },
    { name: 'Speak-No-Evil Monkey', emoji: '🙊' },
    { name: 'Collision', emoji: '💥' },
    { name: 'Dizzy', emoji: '💫' },
    { name: 'Sweat Droplets', emoji: '💦' },
    { name: 'Dashing Away', emoji: '💨' },
    { name: 'Monkey Face', emoji: '🐵' },
    { name: 'Monkey', emoji: '🐒' },
    { name: 'Gorilla', emoji: '🦍' },
    { name: 'Orangutan', emoji: '🦧' },
    { name: 'Dog Face', emoji: '🐶' },
    { name: 'Dog', emoji: '🐕' },
    { name: 'Guide Dog', emoji: '🦮' },
    { name: 'Service Dog', emoji: '🐕‍🦺' },
    { name: 'Poodle', emoji: '🐩' },
    { name: 'Wolf', emoji: '🐺' },
    { name: 'Fox', emoji: '🦊' },
    { name: 'Raccoon', emoji: '🦝' },
    { name: 'Cat Face', emoji: '🐱' },
    { name: 'Cat', emoji: '🐈' },
    { name: 'Lion', emoji: '🦁' },
    { name: 'Tiger Face', emoji: '🐯' },
    { name: 'Tiger', emoji: '🐅' },
    { name: 'Leopard', emoji: '🐆' },
    { name: 'Horse Face', emoji: '🐴' },
    { name: 'Horse', emoji: '🐎' },
    { name: 'Unicorn', emoji: '🦄' },
    { name: 'Zebra', emoji: '🦓' },
    { name: 'Deer', emoji: '🦌' },
    { name: 'Cow Face', emoji: '🐮' },
    { name: 'Ox', emoji: '🐂' },
    { name: 'Water Buffalo', emoji: '🐃' },
    { name: 'Cow', emoji: '🐄' },
    { name: 'Pig Face', emoji: '🐷' },
    { name: 'Pig', emoji: '🐖' },
    { name: 'Boar', emoji: '🐗' },
    { name: 'Pig Nose', emoji: '🐽' },
    { name: 'Ram', emoji: '🐏' },
    { name: 'Ewe', emoji: '🐑' },
    { name: 'Goat', emoji: '🐐' },
    { name: 'Camel', emoji: '🐪' },
    { name: 'Two-Hump Camel', emoji: '🐫' },
    { name: 'Llama', emoji: '🦙' },
    { name: 'Giraffe', emoji: '🦒' },
    { name: 'Elephant', emoji: '🐘' },
    { name: 'Rhinoceros', emoji: '🦏' },
    { name: 'Hippopotamus', emoji: '🦛' },
    { name: 'Mouse Face', emoji: '🐭' },
    { name: 'Mouse', emoji: '🐁' },
    { name: 'Rat', emoji: '🐀' },
    { name: 'Hamster', emoji: '🐹' },
    { name: 'Rabbit Face', emoji: '🐰' },
    { name: 'Rabbit', emoji: '🐇' },
    { name: 'Chipmunk', emoji: '🐿' },
    { name: 'Hedgehog', emoji: '🦔' },
    { name: 'Bat', emoji: '🦇' },
    { name: 'Bear', emoji: '🐻' },
    { name: 'Koala', emoji: '🐨' },
    { name: 'Panda', emoji: '🐼' },
    { name: 'Sloth', emoji: '🦥' },
    { name: 'Otter', emoji: '🦦' },
    { name: 'Skunk', emoji: '🦨' },
    { name: 'Kangaroo', emoji: '🦘' },
    { name: 'Badger', emoji: '🦡' },
    { name: 'Paw Prints', emoji: '🐾' },
    { name: 'Turkey', emoji: '🦃' },
    { name: 'Chicken', emoji: '🐔' },
    { name: 'Rooster', emoji: '🐓' },
    { name: 'Hatching Chick', emoji: '🐣' },
    { name: 'Baby Chick', emoji: '🐤' },
    { name: 'Front-Facing Baby Chick', emoji: '🐥' },
    { name: 'Bird', emoji: '🐦' },
    { name: 'Penguin', emoji: '🐧' },
    { name: 'Dove', emoji: '🕊' },
    { name: 'Eagle', emoji: '🦅' },
    { name: 'Duck', emoji: '🦆' },
    { name: 'Swan', emoji: '🦢' },
    { name: 'Owl', emoji: '🦉' },
    { name: 'Flamingo', emoji: '🦩' },
    { name: 'Peacock', emoji: '🦚' },
    { name: 'Parrot', emoji: '🦜' },
    { name: 'Frog', emoji: '🐸' },
    { name: 'Crocodile', emoji: '🐊' },
    { name: 'Turtle', emoji: '🐢' },
    { name: 'Lizard', emoji: '🦎' },
    { name: 'Snake', emoji: '🐍' },
    { name: 'Dragon Face', emoji: '🐲' },
    { name: 'Dragon', emoji: '🐉' },
    { name: 'Sauropod', emoji: '🦕' },
    { name: 'T-Rex', emoji: '🦖' },
    { name: 'Spouting Whale', emoji: '🐳' },
    { name: 'Whale', emoji: '🐋' },
    { name: 'Dolphin', emoji: '🐬' },
    { name: 'Fish', emoji: '🐟' },
    { name: 'Tropical Fish', emoji: '🐠' },
    { name: 'Blowfish', emoji: '🐡' },
    { name: 'Shark', emoji: '🦈' },
    { name: 'Octopus', emoji: '🐙' },
    { name: 'Spiral Shell', emoji: '🐚' },
    { name: 'Snail', emoji: '🐌' },
    { name: 'Butterfly', emoji: '🦋' },
    { name: 'Bug', emoji: '🐛' },
    { name: 'Ant', emoji: '🐜' },
    { name: 'Honeybee', emoji: '🐝' },
    { name: 'Lady Beetle', emoji: '🐞' },
    { name: 'Cricket', emoji: '🦗' },
    { name: 'Spider', emoji: '🕷' },
    { name: 'Spider Web', emoji: '🕸' },
    { name: 'Scorpion', emoji: '🦂' },
    { name: 'Mosquito', emoji: '🦟' },
    { name: 'Microbe', emoji: '🦠' },
    { name: 'Bouquet', emoji: '💐' },
    { name: 'Cherry Blossom', emoji: '🌸' },
    { name: 'White Flower', emoji: '💮' },
    { name: 'Rosette', emoji: '🏵' },
    { name: 'Rose', emoji: '🌹' },
    { name: 'Wilted Flower', emoji: '🥀' },
    { name: 'Hibiscus', emoji: '🌺' },
    { name: 'Sunflower', emoji: '🌻' },
    { name: 'Blossom', emoji: '🌼' },
    { name: 'Tulip', emoji: '🌷' },
    { name: 'Seedling', emoji: '🌱' },
    { name: 'Evergreen Tree', emoji: '🌲' },
    { name: 'Deciduous Tree', emoji: '🌳' },
    { name: 'Palm Tree', emoji: '🌴' },
    { name: 'Cactus', emoji: '🌵' },
    { name: 'Sheaf of Rice', emoji: '🌾' },
    { name: 'Herb', emoji: '🌿' },
    { name: 'Shamrock', emoji: '☘️' },
    { name: 'Four Leaf Clover', emoji: '🍀' },
    { name: 'Maple Leaf', emoji: '🍁' },
    { name: 'Fallen Leaf', emoji: '🍂' },
    { name: 'Leaf Fluttering in Wind', emoji: '🍃' },
    { name: 'Mushroom', emoji: '🍄' },
    { name: 'Chestnut', emoji: '🌰' },
    { name: 'Crab', emoji: '🦀' },
    { name: 'Lobster', emoji: '🦞' },
    { name: 'Shrimp', emoji: '🦐' },
    { name: 'Squid', emoji: '🦑' },
    { name: 'Globe Showing Europe-Africa', emoji: '🌍' },
    { name: 'Globe Showing Americas', emoji: '🌎' },
    { name: 'Globe Showing Asia-Australia', emoji: '🌏' },
    { name: 'Globe with Meridians', emoji: '🌐' },
    { name: 'New Moon', emoji: '🌑' },
    { name: 'Waxing Crescent Moon', emoji: '🌒' },
    { name: 'First Quarter Moon', emoji: '🌓' },
    { name: 'Waxing Gibbous Moon', emoji: '🌔' },
    { name: 'Full Moon', emoji: '🌕' },
    { name: 'Waning Gibbous Moon', emoji: '🌖' },
    { name: 'Last Quarter Moon', emoji: '🌗' },
    { name: 'Waning Crescent Moon', emoji: '🌘' },
    { name: 'Crescent Moon', emoji: '🌙' },
    { name: 'New Moon Face', emoji: '🌚' },
    { name: 'First Quarter Moon Face', emoji: '🌛' },
    { name: 'Last Quarter Moon Face', emoji: '🌜' },
    { name: 'Sun', emoji: '☀️' },
    { name: 'Full Moon Face', emoji: '🌝' },
    { name: 'Sun with Face', emoji: '🌞' },
    { name: 'Star', emoji: '⭐' },
    { name: 'Glowing Star', emoji: '🌟' },
    { name: 'Shooting Star', emoji: '🌠' },
    { name: 'Cloud', emoji: '☁️' },
    { name: 'Sun Behind Cloud', emoji: '⛅' },
    { name: 'Cloud with Lightning and Rain', emoji: '⛈' },
    { name: 'Sun Behind Small Cloud', emoji: '🌤' },
    { name: 'Sun Behind Large Cloud', emoji: '🌥' },
    { name: 'Sun Behind Rain Cloud', emoji: '🌦' },
    { name: 'Cloud with Rain', emoji: '🌧' },
    { name: 'Cloud with Snow', emoji: '🌨' },
    { name: 'Cloud with Lightning', emoji: '🌩' },
    { name: 'Tornado', emoji: '🌪' },
    { name: 'Fog', emoji: '🌫' },
    { name: 'Wind Face', emoji: '🌬' },
    { name: 'Rainbow', emoji: '🌈' },
    { name: 'Umbrella', emoji: '☂️' },
    { name: 'Umbrella with Rain Drops', emoji: '☔' },
    { name: 'High Voltage', emoji: '⚡' },
    { name: 'Snowflake', emoji: '❄️' },
    { name: 'Snowman', emoji: '☃️' },
    { name: 'Snowman Without Snow', emoji: '⛄' },
    { name: 'Comet', emoji: '☄️' },
    { name: 'Fire', emoji: '🔥' },
    { name: 'Droplet', emoji: '💧' },
    { name: 'Water Wave', emoji: '🌊' },
    { name: 'Christmas Tree', emoji: '🎄' },
    { name: 'Sparkles', emoji: '✨' },
    { name: 'Tanabata Tree', emoji: '🎋' },
    { name: 'Pine Decoration', emoji: '🎍' }
  ]
}
