export default {
  emojis: [
    { name: 'Chequered Flag', emoji: '🏁' },
    { name: 'Triangular Flag', emoji: '🚩' },
    { name: 'Crossed Flags', emoji: '🎌' },
    { name: 'Black Flag', emoji: '🏴' },
    { name: 'White Flag', emoji: '🏳' },
    { name: 'Rainbow Flag', emoji: '🏳️‍🌈' },
    { name: 'Transgender Flag', emoji: '🏳️‍⚧️' },
    { name: 'Pirate Flag', emoji: '🏴‍☠️' },
    { name: 'Flag: Ascension Island', emoji: '🇦🇨' },
    { name: 'Flag: Andorra', emoji: '🇦🇩' },
    { name: 'Flag: United Arab Emirates', emoji: '🇦🇪' },
    { name: 'Flag: Afghanistan', emoji: '🇦🇫' },
    { name: 'Flag: Antigua & Barbuda', emoji: '🇦🇬' },
    { name: 'Flag: Anguilla', emoji: '🇦🇮' },
    { name: 'Flag: Albania', emoji: '🇦🇱' },
    { name: 'Flag: Armenia', emoji: '🇦🇲' },
    { name: 'Flag: Angola', emoji: '🇦🇴' },
    { name: 'Flag: Antarctica', emoji: '🇦🇶' },
    { name: 'Flag: Argentina', emoji: '🇦🇷' },
    { name: 'Flag: American Samoa', emoji: '🇦🇸' },
    { name: 'Flag: Austria', emoji: '🇦🇹' },
    { name: 'Flag: Australia', emoji: '🇦🇺' },
    { name: 'Flag: Aruba', emoji: '🇦🇼' },
    { name: 'Flag: Åland Islands', emoji: '🇦🇽' },
    { name: 'Flag: Azerbaijan', emoji: '🇦🇿' },
    { name: 'Flag: Bosnia & Herzegovina', emoji: '🇧🇦' },
    { name: 'Flag: Barbados', emoji: '🇧🇧' },
    { name: 'Flag: Bangladesh', emoji: '🇧🇩' },
    { name: 'Flag: Belgium', emoji: '🇧🇪' },
    { name: 'Flag: Burkina Faso', emoji: '🇧🇫' },
    { name: 'Flag: Bulgaria', emoji: '🇧🇬' },
    { name: 'Flag: Bahrain', emoji: '🇧🇭' },
    { name: 'Flag: Burundi', emoji: '🇧🇮' },
    { name: 'Flag: Benin', emoji: '🇧🇯' },
    { name: 'Flag: St. Barthélemy', emoji: '🇧🇱' },
    { name: 'Flag: Bermuda', emoji: '🇧🇲' },
    { name: 'Flag: Brunei', emoji: '🇧🇳' },
    { name: 'Flag: Bolivia', emoji: '🇧🇴' },
    { name: 'Flag: Caribbean Netherlands', emoji: '🇧🇶' },
    { name: 'Flag: Brazil', emoji: '🇧🇷' },
    { name: 'Flag: Bahamas', emoji: '🇧🇸' },
    { name: 'Flag: Bhutan', emoji: '🇧🇹' },
    { name: 'Flag: Bouvet Island', emoji: '🇧🇻' },
    { name: 'Flag: Botswana', emoji: '🇧🇼' },
    { name: 'Flag: Belarus', emoji: '🇧🇾' },
    { name: 'Flag: Belize', emoji: '🇧🇿' },
    { name: 'Flag: Canada', emoji: '🇨🇦' },
    { name: 'Flag: Cocos (Keeling) Islands', emoji: '🇨🇨' },
    { name: 'Flag: Congo - Kinshasa', emoji: '🇨🇩' },
    { name: 'Flag: Central African Republic', emoji: '🇨🇫' },
    { name: 'Flag: Congo - Brazzaville', emoji: '🇨🇬' },
    { name: 'Flag: Switzerland', emoji: '🇨🇭' },
    { name: 'Flag: Côte d’Ivoire', emoji: '🇨🇮' },
    { name: 'Flag: Cook Islands', emoji: '🇨🇰' },
    { name: 'Flag: Chile', emoji: '🇨🇱' },
    { name: 'Flag: Cameroon', emoji: '🇨🇲' },
    { name: 'Flag: China', emoji: '🇨🇳' },
    { name: 'Flag: Colombia', emoji: '🇨🇴' },
    { name: 'Flag: Clipperton Island', emoji: '🇨🇵' },
    { name: 'Flag: Costa Rica', emoji: '🇨🇷' },
    { name: 'Flag: Cuba', emoji: '🇨🇺' },
    { name: 'Flag: Cape Verde', emoji: '🇨🇻' },
    { name: 'Flag: Curaçao', emoji: '🇨🇼' },
    { name: 'Flag: Christmas Island', emoji: '🇨🇽' },
    { name: 'Flag: Cyprus', emoji: '🇨🇾' },
    { name: 'Flag: Czechia', emoji: '🇨🇿' },
    { name: 'Flag: Germany', emoji: '🇩🇪' },
    { name: 'Flag: Diego Garcia', emoji: '🇩🇬' },
    { name: 'Flag: Djibouti', emoji: '🇩🇯' },
    { name: 'Flag: Denmark', emoji: '🇩🇰' },
    { name: 'Flag: Dominica', emoji: '🇩🇲' },
    { name: 'Flag: Dominican Republic', emoji: '🇩🇴' },
    { name: 'Flag: Algeria', emoji: '🇩🇿' },
    { name: 'Flag: Ceuta & Melilla', emoji: '🇪🇦' },
    { name: 'Flag: Ecuador', emoji: '🇪🇨' },
    { name: 'Flag: Estonia', emoji: '🇪🇪' },
    { name: 'Flag: Egypt', emoji: '🇪🇬' },
    { name: 'Flag: Western Sahara', emoji: '🇪🇭' },
    { name: 'Flag: Eritrea', emoji: '🇪🇷' },
    { name: 'Flag: Spain', emoji: '🇪🇸' },
    { name: 'Flag: Ethiopia', emoji: '🇪🇹' },
    { name: 'Flag: European Union', emoji: '🇪🇺' },
    { name: 'Flag: Finland', emoji: '🇫🇮' },
    { name: 'Flag: Fiji', emoji: '🇫🇯' },
    { name: 'Flag: Falkland Islands', emoji: '🇫🇰' },
    { name: 'Flag: Micronesia', emoji: '🇫🇲' },
    { name: 'Flag: Faroe Islands', emoji: '🇫🇴' },
    { name: 'Flag: France', emoji: '🇫🇷' },
    { name: 'Flag: Gabon', emoji: '🇬🇦' },
    { name: 'Flag: United Kingdom', emoji: '🇬🇧' },
    { name: 'Flag: Grenada', emoji: '🇬🇩' },
    { name: 'Flag: Georgia', emoji: '🇬🇪' },
    { name: 'Flag: French Guiana', emoji: '🇬🇫' },
    { name: 'Flag: Guernsey', emoji: '🇬🇬' },
    { name: 'Flag: Ghana', emoji: '🇬🇭' },
    { name: 'Flag: Gibraltar', emoji: '🇬🇮' },
    { name: 'Flag: Greenland', emoji: '🇬🇱' },
    { name: 'Flag: Gambia', emoji: '🇬🇲' },
    { name: 'Flag: Guinea', emoji: '🇬🇳' },
    { name: 'Flag: Guadeloupe', emoji: '🇬🇵' },
    { name: 'Flag: Equatorial Guinea', emoji: '🇬🇶' },
    { name: 'Flag: Greece', emoji: '🇬🇷' },
    { name: 'Flag: South Georgia & South Sandwich Islands', emoji: '🇬🇸' },
    { name: 'Flag: Guatemala', emoji: '🇬🇹' },
    { name: 'Flag: Guam', emoji: '🇬🇺' },
    { name: 'Flag: Guinea-Bissau', emoji: '🇬🇼' },
    { name: 'Flag: Guyana', emoji: '🇬🇾' },
    { name: 'Flag: Hong Kong SAR China', emoji: '🇭🇰' },
    { name: 'Flag: Heard & McDonald Islands', emoji: '🇭🇲' },
    { name: 'Flag: Honduras', emoji: '🇭🇳' },
    { name: 'Flag: Croatia', emoji: '🇭🇷' },
    { name: 'Flag: Haiti', emoji: '🇭🇹' },
    { name: 'Flag: Hungary', emoji: '🇭🇺' },
    { name: 'Flag: Canary Islands', emoji: '🇮🇨' },
    { name: 'Flag: Indonesia', emoji: '🇮🇩' },
    { name: 'Flag: Ireland', emoji: '🇮🇪' },
    { name: 'Flag: Israel', emoji: '🇮🇱' },
    { name: 'Flag: Isle of Man', emoji: '🇮🇲' },
    { name: 'Flag: India', emoji: '🇮🇳' },
    { name: 'Flag: British Indian Ocean Territory', emoji: '🇮🇴' },
    { name: 'Flag: Iraq', emoji: '🇮🇶' },
    { name: 'Flag: Iran', emoji: '🇮🇷' },
    { name: 'Flag: Iceland', emoji: '🇮🇸' },
    { name: 'Flag: Italy', emoji: '🇮🇹' },
    { name: 'Flag: Jersey', emoji: '🇯🇪' },
    { name: 'Flag: Jamaica', emoji: '🇯🇲' },
    { name: 'Flag: Jordan', emoji: '🇯🇴' },
    { name: 'Flag: Japan', emoji: '🇯🇵' },
    { name: 'Flag: Kenya', emoji: '🇰🇪' },
    { name: 'Flag: Kyrgyzstan', emoji: '🇰🇬' },
    { name: 'Flag: Cambodia', emoji: '🇰🇭' },
    { name: 'Flag: Kiribati', emoji: '🇰🇮' },
    { name: 'Flag: Comoros', emoji: '🇰🇲' },
    { name: 'Flag: St. Kitts & Nevis', emoji: '🇰🇳' },
    { name: 'Flag: North Korea', emoji: '🇰🇵' },
    { name: 'Flag: South Korea', emoji: '🇰🇷' },
    { name: 'Flag: Kuwait', emoji: '🇰🇼' },
    { name: 'Flag: Cayman Islands', emoji: '🇰🇾' },
    { name: 'Flag: Kazakhstan', emoji: '🇰🇿' },
    { name: 'Flag: Laos', emoji: '🇱🇦' },
    { name: 'Flag: Lebanon', emoji: '🇱🇧' },
    { name: 'Flag: St. Lucia', emoji: '🇱🇨' },
    { name: 'Flag: Liechtenstein', emoji: '🇱🇮' },
    { name: 'Flag: Sri Lanka', emoji: '🇱🇰' },
    { name: 'Flag: Liberia', emoji: '🇱🇷' },
    { name: 'Flag: Lesotho', emoji: '🇱🇸' },
    { name: 'Flag: Lithuania', emoji: '🇱🇹' },
    { name: 'Flag: Luxembourg', emoji: '🇱🇺' },
    { name: 'Flag: Latvia', emoji: '🇱🇻' },
    { name: 'Flag: Libya', emoji: '🇱🇾' },
    { name: 'Flag: Morocco', emoji: '🇲🇦' },
    { name: 'Flag: Monaco', emoji: '🇲🇨' },
    { name: 'Flag: Moldova', emoji: '🇲🇩' },
    { name: 'Flag: Montenegro', emoji: '🇲🇪' },
    { name: 'Flag: St. Martin', emoji: '🇲🇫' },
    { name: 'Flag: Madagascar', emoji: '🇲🇬' },
    { name: 'Flag: Marshall Islands', emoji: '🇲🇭' },
    { name: 'Flag: North Macedonia', emoji: '🇲🇰' },
    { name: 'Flag: Mali', emoji: '🇲🇱' },
    { name: 'Flag: Myanmar (Burma)', emoji: '🇲🇲' },
    { name: 'Flag: Mongolia', emoji: '🇲🇳' },
    { name: 'Flag: Macao Sar China', emoji: '🇲🇴' },
    { name: 'Flag: Northern Mariana Islands', emoji: '🇲🇵' },
    { name: 'Flag: Martinique', emoji: '🇲🇶' },
    { name: 'Flag: Mauritania', emoji: '🇲🇷' },
    { name: 'Flag: Montserrat', emoji: '🇲🇸' },
    { name: 'Flag: Malta', emoji: '🇲🇹' },
    { name: 'Flag: Mauritius', emoji: '🇲🇺' },
    { name: 'Flag: Maldives', emoji: '🇲🇻' },
    { name: 'Flag: Malawi', emoji: '🇲🇼' },
    { name: 'Flag: Mexico', emoji: '🇲🇽' },
    { name: 'Flag: Malaysia', emoji: '🇲🇾' },
    { name: 'Flag: Mozambique', emoji: '🇲🇿' },
    { name: 'Flag: Namibia', emoji: '🇳🇦' },
    { name: 'Flag: New Caledonia', emoji: '🇳🇨' },
    { name: 'Flag: Niger', emoji: '🇳🇪' },
    { name: 'Flag: Norfolk Island', emoji: '🇳🇫' },
    { name: 'Flag: Nigeria', emoji: '🇳🇬' },
    { name: 'Flag: Nicaragua', emoji: '🇳🇮' },
    { name: 'Flag: Netherlands', emoji: '🇳🇱' },
    { name: 'Flag: Norway', emoji: '🇳🇴' },
    { name: 'Flag: Nepal', emoji: '🇳🇵' },
    { name: 'Flag: Nauru', emoji: '🇳🇷' },
    { name: 'Flag: Niue', emoji: '🇳🇺' },
    { name: 'Flag: New Zealand', emoji: '🇳🇿' },
    { name: 'Flag: Oman', emoji: '🇴🇲' },
    { name: 'Flag: Panama', emoji: '🇵🇦' },
    { name: 'Flag: Peru', emoji: '🇵🇪' },
    { name: 'Flag: French Polynesia', emoji: '🇵🇫' },
    { name: 'Flag: Papua New Guinea', emoji: '🇵🇬' },
    { name: 'Flag: Philippines', emoji: '🇵🇭' },
    { name: 'Flag: Pakistan', emoji: '🇵🇰' },
    { name: 'Flag: Poland', emoji: '🇵🇱' },
    { name: 'Flag: St. Pierre & Miquelon', emoji: '🇵🇲' },
    { name: 'Flag: Pitcairn Islands', emoji: '🇵🇳' },
    { name: 'Flag: Puerto Rico', emoji: '🇵🇷' },
    { name: 'Flag: Palestinian Territories', emoji: '🇵🇸' },
    { name: 'Flag: Portugal', emoji: '🇵🇹' },
    { name: 'Flag: Palau', emoji: '🇵🇼' },
    { name: 'Flag: Paraguay', emoji: '🇵🇾' },
    { name: 'Flag: Qatar', emoji: '🇶🇦' },
    { name: 'Flag: Réunion', emoji: '🇷🇪' },
    { name: 'Flag: Romania', emoji: '🇷🇴' },
    { name: 'Flag: Serbia', emoji: '🇷🇸' },
    { name: 'Flag: Russia', emoji: '🇷🇺' },
    { name: 'Flag: Rwanda', emoji: '🇷🇼' },
    { name: 'Flag: Saudi Arabia', emoji: '🇸🇦' },
    { name: 'Flag: Solomon Islands', emoji: '🇸🇧' },
    { name: 'Flag: Seychelles', emoji: '🇸🇨' },
    { name: 'Flag: Sudan', emoji: '🇸🇩' },
    { name: 'Flag: Sweden', emoji: '🇸🇪' },
    { name: 'Flag: Singapore', emoji: '🇸🇬' },
    { name: 'Flag: St. Helena', emoji: '🇸🇭' },
    { name: 'Flag: Slovenia', emoji: '🇸🇮' },
    { name: 'Flag: Svalbard & Jan Mayen', emoji: '🇸🇯' },
    { name: 'Flag: Slovakia', emoji: '🇸🇰' },
    { name: 'Flag: Sierra Leone', emoji: '🇸🇱' },
    { name: 'Flag: San Marino', emoji: '🇸🇲' },
    { name: 'Flag: Senegal', emoji: '🇸🇳' },
    { name: 'Flag: Somalia', emoji: '🇸🇴' },
    { name: 'Flag: Suriname', emoji: '🇸🇷' },
    { name: 'Flag: South Sudan', emoji: '🇸🇸' },
    { name: 'Flag: São Tomé & Príncipe', emoji: '🇸🇹' },
    { name: 'Flag: El Salvador', emoji: '🇸🇻' },
    { name: 'Flag: Sint Maarten', emoji: '🇸🇽' },
    { name: 'Flag: Syria', emoji: '🇸🇾' },
    { name: 'Flag: Eswatini', emoji: '🇸🇿' },
    { name: 'Flag: Tristan Da Cunha', emoji: '🇹🇦' },
    { name: 'Flag: Turks & Caicos Islands', emoji: '🇹🇨' },
    { name: 'Flag: Chad', emoji: '🇹🇩' },
    { name: 'Flag: French Southern Territories', emoji: '🇹🇫' },
    { name: 'Flag: Togo', emoji: '🇹🇬' },
    { name: 'Flag: Thailand', emoji: '🇹🇭' },
    { name: 'Flag: Tajikistan', emoji: '🇹🇯' },
    { name: 'Flag: Tokelau', emoji: '🇹🇰' },
    { name: 'Flag: Timor-Leste', emoji: '🇹🇱' },
    { name: 'Flag: Turkmenistan', emoji: '🇹🇲' },
    { name: 'Flag: Tunisia', emoji: '🇹🇳' },
    { name: 'Flag: Tonga', emoji: '🇹🇴' },
    { name: 'Flag: Turkey', emoji: '🇹🇷' },
    { name: 'Flag: Trinidad & Tobago', emoji: '🇹🇹' },
    { name: 'Flag: Tuvalu', emoji: '🇹🇻' },
    { name: 'Flag: Taiwan', emoji: '🇹🇼' },
    { name: 'Flag: Tanzania', emoji: '🇹🇿' },
    { name: 'Flag: Ukraine', emoji: '🇺🇦' },
    { name: 'Flag: Uganda', emoji: '🇺🇬' },
    { name: 'Flag: U.S. Outlying Islands', emoji: '🇺🇲' },
    { name: 'Flag: United Nations', emoji: '🇺🇳' },
    { name: 'Flag: United States', emoji: '🇺🇸' },
    { name: 'Flag: Uruguay', emoji: '🇺🇾' },
    { name: 'Flag: Uzbekistan', emoji: '🇺🇿' },
    { name: 'Flag: Vatican City', emoji: '🇻🇦' },
    { name: 'Flag: St. Vincent & Grenadines', emoji: '🇻🇨' },
    { name: 'Flag: Venezuela', emoji: '🇻🇪' },
    { name: 'Flag: British Virgin Islands', emoji: '🇻🇬' },
    { name: 'Flag: U.S. Virgin Islands', emoji: '🇻🇮' },
    { name: 'Flag: Vietnam', emoji: '🇻🇳' },
    { name: 'Flag: Vanuatu', emoji: '🇻🇺' },
    { name: 'Flag: Wallis & Futuna', emoji: '🇼🇫' },
    { name: 'Flag: Samoa', emoji: '🇼🇸' },
    { name: 'Flag: Kosovo', emoji: '🇽🇰' },
    { name: 'Flag: Yemen', emoji: '🇾🇪' },
    { name: 'Flag: Mayotte', emoji: '🇾🇹' },
    { name: 'Flag: South Africa', emoji: '🇿🇦' },
    { name: 'Flag: Zambia', emoji: '🇿🇲' },
    { name: 'Flag: Zimbabwe', emoji: '🇿🇼' },
    { name: 'Flag: England', emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
    { name: 'Flag: Scotland', emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
    { name: 'Flag: Wales', emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
    { name: 'Flag for Texas (US-TX)', emoji: '🏴󠁵󠁳󠁴󠁸󠁿' }
  ]
}
