export default {
  name: 'Food & Drink',
  emojis: [
    { name: 'Grapes', emoji: '🍇' },
    { name: 'Melon', emoji: '🍈' },
    { name: 'Watermelon', emoji: '🍉' },
    { name: 'Tangerine', emoji: '🍊' },
    { name: 'Lemon', emoji: '🍋' },
    { name: 'Banana', emoji: '🍌' },
    { name: 'Pineapple', emoji: '🍍' },
    { name: 'Mango', emoji: '🥭' },
    { name: 'Red Apple', emoji: '🍎' },
    { name: 'Green Apple', emoji: '🍏' },
    { name: 'Pear', emoji: '🍐' },
    { name: 'Peach', emoji: '🍑' },
    { name: 'Cherries', emoji: '🍒' },
    { name: 'Strawberry', emoji: '🍓' },
    { name: 'Kiwi Fruit', emoji: '🥝' },
    { name: 'Tomato', emoji: '🍅' },
    { name: 'Coconut', emoji: '🥥' },
    { name: 'Avocado', emoji: '🥑' },
    { name: 'Eggplant', emoji: '🍆' },
    { name: 'Potato', emoji: '🥔' },
    { name: 'Carrot', emoji: '🥕' },
    { name: 'Ear of Corn', emoji: '🌽' },
    { name: 'Hot Pepper', emoji: '🌶' },
    { name: 'Cucumber', emoji: '🥒' },
    { name: 'Leafy Green', emoji: '🥬' },
    { name: 'Broccoli', emoji: '🥦' },
    { name: 'Garlic', emoji: '🧄' },
    { name: 'Onion', emoji: '🧅' },
    { name: 'Mushroom', emoji: '🍄' },
    { name: 'Peanuts', emoji: '🥜' },
    { name: 'Chestnut', emoji: '🌰' },
    { name: 'Bread', emoji: '🍞' },
    { name: 'Croissant', emoji: '🥐' },
    { name: 'Baguette Bread', emoji: '🥖' },
    { name: 'Pretzel', emoji: '🥨' },
    { name: 'Bagel', emoji: '🥯' },
    { name: 'Pancakes', emoji: '🥞' },
    { name: 'Waffle', emoji: '🧇' },
    { name: 'Cheese Wedge', emoji: '🧀' },
    { name: 'Meat on Bone', emoji: '🍖' },
    { name: 'Poultry Leg', emoji: '🍗' },
    { name: 'Cut of Meat', emoji: '🥩' },
    { name: 'Bacon', emoji: '🥓' },
    { name: 'Hamburger', emoji: '🍔' },
    { name: 'French Fries', emoji: '🍟' },
    { name: 'Pizza', emoji: '🍕' },
    { name: 'Hot Dog', emoji: '🌭' },
    { name: 'Sandwich', emoji: '🥪' },
    { name: 'Taco', emoji: '🌮' },
    { name: 'Burrito', emoji: '🌯' },
    { name: 'Stuffed Flatbread', emoji: '🥙' },
    { name: 'Falafel', emoji: '🧆' },
    { name: 'Egg', emoji: '🥚' },
    { name: 'Cooking', emoji: '🍳' },
    { name: 'Shallow Pan of Food', emoji: '🥘' },
    { name: 'Pot of Food', emoji: '🍲' },
    { name: 'Bowl with Spoon', emoji: '🥣' },
    { name: 'Green Salad', emoji: '🥗' },
    { name: 'Popcorn', emoji: '🍿' },
    { name: 'Butter', emoji: '🧈' },
    { name: 'Salt', emoji: '🧂' },
    { name: 'Canned Food', emoji: '🥫' },
    { name: 'Bento Box', emoji: '🍱' },
    { name: 'Rice Cracker', emoji: '🍘' },
    { name: 'Rice Ball', emoji: '🍙' },
    { name: 'Cooked Rice', emoji: '🍚' },
    { name: 'Curry Rice', emoji: '🍛' },
    { name: 'Steaming Bowl', emoji: '🍜' },
    { name: 'Spaghetti', emoji: '🍝' },
    { name: 'Roasted Sweet Potato', emoji: '🍠' },
    { name: 'Oden', emoji: '🍢' },
    { name: 'Sushi', emoji: '🍣' },
    { name: 'Fried Shrimp', emoji: '🍤' },
    { name: 'Fish Cake with Swirl', emoji: '🍥' },
    { name: 'Moon Cake', emoji: '🥮' },
    { name: 'Dango', emoji: '🍡' },
    { name: 'Dumpling', emoji: '🥟' },
    { name: 'Fortune Cookie', emoji: '🥠' },
    { name: 'Takeout Box', emoji: '🥡' },
    { name: 'Oyster', emoji: '🦪' },
    { name: 'Soft Ice Cream', emoji: '🍦' },
    { name: 'Shaved Ice', emoji: '🍧' },
    { name: 'Ice Cream', emoji: '🍨' },
    { name: 'Doughnut', emoji: '🍩' },
    { name: 'Cookie', emoji: '🍪' },
    { name: 'Birthday Cake', emoji: '🎂' },
    { name: 'Shortcake', emoji: '🍰' },
    { name: 'Cupcake', emoji: '🧁' },
    { name: 'Pie', emoji: '🥧' },
    { name: 'Chocolate Bar', emoji: '🍫' },
    { name: 'Candy', emoji: '🍬' },
    { name: 'Lollipop', emoji: '🍭' },
    { name: 'Custard', emoji: '🍮' },
    { name: 'Honey Pot', emoji: '🍯' },
    { name: 'Baby Bottle', emoji: '🍼' },
    { name: 'Glass of Milk', emoji: '🥛' },
    { name: 'Hot Beverage', emoji: '☕' },
    { name: 'Teacup Without Handle', emoji: '🍵' },
    { name: 'Sake', emoji: '🍶' },
    { name: 'Bottle with Popping Cork', emoji: '🍾' },
    { name: 'Wine Glass', emoji: '🍷' },
    { name: 'Cocktail Glass', emoji: '🍸' },
    { name: 'Tropical Drink', emoji: '🍹' },
    { name: 'Beer Mug', emoji: '🍺' },
    { name: 'Clinking Beer Mugs', emoji: '🍻' },
    { name: 'Clinking Glasses', emoji: '🥂' },
    { name: 'Tumbler Glass', emoji: '🥃' },
    { name: 'Cup with Straw', emoji: '🥤' },
    { name: 'Beverage Box', emoji: '🧃' },
    { name: 'Mate', emoji: '🧉' },
    { name: 'Ice', emoji: '🧊' },
    { name: 'Chopsticks', emoji: '🥢' },
    { name: 'Fork and Knife with Plate', emoji: '🍽' },
    { name: 'Fork and Knife', emoji: '🍴' },
    { name: 'Spoon', emoji: '🥄' }
  ]
}
