export default {
  emojis: [
    { name: 'Love Letter', emoji: '💌' },
    { name: 'Hole', emoji: '🕳' },
    { name: 'Bomb', emoji: '💣' },
    { name: 'Person Taking Bath', emoji: '🛀' },
    { name: 'Person in Bed', emoji: '🛌' },
    { name: 'Kitchen Knife', emoji: '🔪' },
    { name: 'Amphora', emoji: '🏺' },
    { name: 'World Map', emoji: '🗺' },
    { name: 'Compass', emoji: '🧭' },
    { name: 'Brick', emoji: '🧱' },
    { name: 'Barber Pole', emoji: '💈' },
    { name: 'Manual Wheelchair', emoji: '🦽' },
    { name: 'Motorized Wheelchair', emoji: '🦼' },
    { name: 'Oil Drum', emoji: '🛢' },
    { name: 'Bellhop Bell', emoji: '🛎' },
    { name: 'Luggage', emoji: '🧳' },
    { name: 'Hourglass Done', emoji: '⌛' },
    { name: 'Hourglass Not Done', emoji: '⏳' },
    { name: 'Watch', emoji: '⌚' },
    { name: 'Alarm Clock', emoji: '⏰' },
    { name: 'Stopwatch', emoji: '⏱' },
    { name: 'Timer Clock', emoji: '⏲' },
    { name: 'Mantelpiece Clock', emoji: '🕰' },
    { name: 'Thermometer', emoji: '🌡' },
    { name: 'Umbrella on Ground', emoji: '⛱' },
    { name: 'Firecracker', emoji: '🧨' },
    { name: 'Balloon', emoji: '🎈' },
    { name: 'Party Popper', emoji: '🎉' },
    { name: 'Confetti Ball', emoji: '🎊' },
    { name: 'Japanese Dolls', emoji: '🎎' },
    { name: 'Carp Streamer', emoji: '🎏' },
    { name: 'Wind Chime', emoji: '🎐' },
    { name: 'Red Envelope', emoji: '🧧' },
    { name: 'Ribbon', emoji: '🎀' },
    { name: 'Wrapped Gift', emoji: '🎁' },
    { name: 'Diving Mask', emoji: '🤿' },
    { name: 'Yo-Yo', emoji: '🪀' },
    { name: 'Kite', emoji: '🪁' },
    { name: 'Crystal Ball', emoji: '🔮' },
    { name: 'Nazar Amulet', emoji: '🧿' },
    { name: 'Joystick', emoji: '🕹' },
    { name: 'Teddy Bear', emoji: '🧸' },
    { name: 'Framed Picture', emoji: '🖼' },
    { name: 'Thread', emoji: '🧵' },
    { name: 'Yarn', emoji: '🧶' },
    { name: 'Shopping Bags', emoji: '🛍' },
    { name: 'Prayer Beads', emoji: '📿' },
    { name: 'Gem Stone', emoji: '💎' },
    { name: 'Postal Horn', emoji: '📯' },
    { name: 'Studio Microphone', emoji: '🎙' },
    { name: 'Level Slider', emoji: '🎚' },
    { name: 'Control Knobs', emoji: '🎛' },
    { name: 'Radio', emoji: '📻' },
    { name: 'Banjo', emoji: '🪕' },
    { name: 'Mobile Phone', emoji: '📱' },
    { name: 'Mobile Phone with Arrow', emoji: '📲' },
    { name: 'Telephone', emoji: '☎' },
    { name: 'Telephone Receiver', emoji: '📞' },
    { name: 'Pager', emoji: '📟' },
    { name: 'Fax Machine', emoji: '📠' },
    { name: 'Battery', emoji: '🔋' },
    { name: 'Electric Plug', emoji: '🔌' },
    { name: 'Laptop', emoji: '💻' },
    { name: 'Desktop Computer', emoji: '🖥' },
    { name: 'Printer', emoji: '🖨' },
    { name: 'Keyboard', emoji: '⌨' },
    { name: 'Computer Mouse', emoji: '🖱' },
    { name: 'Trackball', emoji: '🖲' },
    { name: 'Computer Disk', emoji: '💽' },
    { name: 'Floppy Disk', emoji: '💾' },
    { name: 'Optical Disk', emoji: '💿' },
    { name: 'DVD', emoji: '📀' },
    { name: 'Abacus', emoji: '🧮' },
    { name: 'Movie Camera', emoji: '🎥' },
    { name: 'Film Frames', emoji: '🎞' },
    { name: 'Film Projector', emoji: '📽' },
    { name: 'Television', emoji: '📺' },
    { name: 'Camera', emoji: '📷' },
    { name: 'Camera with Flash', emoji: '📸' },
    { name: 'Video Camera', emoji: '📹' },
    { name: 'Videocassette', emoji: '📼' },
    { name: 'Magnifying Glass Tilted Left', emoji: '🔍' },
    { name: 'Magnifying Glass Tilted Right', emoji: '🔎' },
    { name: 'Candle', emoji: '🕯' },
    { name: 'Light Bulb', emoji: '💡' },
    { name: 'Flashlight', emoji: '🔦' },
    { name: 'Red Paper Lantern', emoji: '🏮' },
    { name: 'Diya Lamp', emoji: '🪔' },
    { name: 'Notebook with Decorative Cover', emoji: '📔' },
    { name: 'Closed Book', emoji: '📕' },
    { name: 'Open Book', emoji: '📖' },
    { name: 'Green Book', emoji: '📗' },
    { name: 'Blue Book', emoji: '📘' },
    { name: 'Orange Book', emoji: '📙' },
    { name: 'Books', emoji: '📚' },
    { name: 'Notebook', emoji: '📓' },
    { name: 'Ledger', emoji: '📒' },
    { name: 'Page with Curl', emoji: '📃' },
    { name: 'Scroll', emoji: '📜' },
    { name: 'Page Facing Up', emoji: '📄' },
    { name: 'Newspaper', emoji: '📰' },
    { name: 'Rolled-Up Newspaper', emoji: '🗞' },
    { name: 'Bookmark Tabs', emoji: '📑' },
    { name: 'Bookmark', emoji: '🔖' },
    { name: 'Label', emoji: '🏷' },
    { name: 'Money Bag', emoji: '💰' },
    { name: 'Yen Banknote', emoji: '💴' },
    { name: 'Dollar Banknote', emoji: '💵' },
    { name: 'Euro Banknote', emoji: '💶' },
    { name: 'Pound Banknote', emoji: '💷' },
    { name: 'Money with Wings', emoji: '💸' },
    { name: 'Credit Card', emoji: '💳' },
    { name: 'Receipt', emoji: '🧾' },
    { name: 'Envelope', emoji: '✉' },
    { name: 'E-Mail', emoji: '📧' },
    { name: 'Incoming Envelope', emoji: '📨' },
    { name: 'Envelope with Arrow', emoji: '📩' },
    { name: 'Outbox Tray', emoji: '📤' },
    { name: 'Inbox Tray', emoji: '📥' },
    { name: 'Package', emoji: '📦' },
    { name: 'Closed Mailbox with Raised Flag', emoji: '📫' },
    { name: 'Closed Mailbox with Lowered Flag', emoji: '📪' },
    { name: 'Open Mailbox with Raised Flag', emoji: '📬' },
    { name: 'Open Mailbox with Lowered Flag', emoji: '📭' },
    { name: 'Postbox', emoji: '📮' },
    { name: 'Ballot Box with Ballot', emoji: '🗳' },
    { name: 'Pencil', emoji: '✏' },
    { name: 'Black Nib', emoji: '✒' },
    { name: 'Fountain Pen', emoji: '🖋' },
    { name: 'Pen', emoji: '🖊' },
    { name: 'Paintbrush', emoji: '🖌' },
    { name: 'Crayon', emoji: '🖍' },
    { name: 'Memo', emoji: '📝' },
    { name: 'File Folder', emoji: '📁' },
    { name: 'Open File Folder', emoji: '📂' },
    { name: 'Card Index Dividers', emoji: '🗂' },
    { name: 'Calendar', emoji: '📅' },
    { name: 'Tear-Off Calendar', emoji: '📆' },
    { name: 'Spiral Notepad', emoji: '🗒' },
    { name: 'Spiral Calendar', emoji: '🗓' },
    { name: 'Card Index', emoji: '📇' },
    { name: 'Chart Increasing', emoji: '📈' },
    { name: 'Chart Decreasing', emoji: '📉' },
    { name: 'Bar Chart', emoji: '📊' },
    { name: 'Clipboard', emoji: '📋' },
    { name: 'Pushpin', emoji: '📌' },
    { name: 'Round Pushpin', emoji: '📍' },
    { name: 'Paperclip', emoji: '📎' },
    { name: 'Linked Paperclips', emoji: '🖇' },
    { name: 'Straight Ruler', emoji: '📏' },
    { name: 'Triangular Ruler', emoji: '📐' },
    { name: 'Scissors', emoji: '✂' },
    { name: 'Card File Box', emoji: '🗃' },
    { name: 'File Cabinet', emoji: '🗄' },
    { name: 'Wastebasket', emoji: '🗑' },
    { name: 'Locked', emoji: '🔒' },
    { name: 'Unlocked', emoji: '🔓' },
    { name: 'Locked with Pen', emoji: '🔏' },
    { name: 'Locked with Key', emoji: '🔐' },
    { name: 'Key', emoji: '🔑' },
    { name: 'Old Key', emoji: '🗝' },
    { name: 'Hammer', emoji: '🔨' },
    { name: 'Axe', emoji: '🪓' },
    { name: 'Pick', emoji: '⛏' },
    { name: 'Hammer and Pick', emoji: '⚒' },
    { name: 'Hammer and Wrench', emoji: '🛠' },
    { name: 'Dagger', emoji: '🗡' },
    { name: 'Crossed Swords', emoji: '⚔' },
    { name: 'Pistol', emoji: '🔫' },
    { name: 'Shield', emoji: '🛡' },
    { name: 'Wrench', emoji: '🔧' },
    { name: 'Nut and Bolt', emoji: '🔩' },
    { name: 'Gear', emoji: '⚙' },
    { name: 'Clamp', emoji: '🗜' },
    { name: 'Balance Scale', emoji: '⚖' },
    { name: 'White Cane', emoji: '🦯' },
    { name: 'Link', emoji: '🔗' },
    { name: 'Chains', emoji: '⛓' },
    { name: 'Toolbox', emoji: '🧰' },
    { name: 'Magnet', emoji: '🧲' },
    { name: 'Alembic', emoji: '⚗' },
    { name: 'Test Tube', emoji: '🧪' },
    { name: 'Petri Dish', emoji: '🧫' },
    { name: 'DNA', emoji: '🧬' },
    { name: 'Microscope', emoji: '🔬' },
    { name: 'Telescope', emoji: '🔭' },
    { name: 'Satellite Antenna', emoji: '📡' },
    { name: 'Syringe', emoji: '💉' },
    { name: 'Drop of Blood', emoji: '🩸' },
    { name: 'Pill', emoji: '💊' },
    { name: 'Adhesive Bandage', emoji: '🩹' },
    { name: 'Stethoscope', emoji: '🩺' },
    { name: 'Door', emoji: '🚪' },
    { name: 'Bed', emoji: '🛏' },
    { name: 'Couch and Lamp', emoji: '🛋' },
    { name: 'Chair', emoji: '🪑' },
    { name: 'Toilet', emoji: '🚽' },
    { name: 'Shower', emoji: '🚿' },
    { name: 'Bathtub', emoji: '🛁' },
    { name: 'Razor', emoji: '🪒' },
    { name: 'Lotion Bottle', emoji: '🧴' },
    { name: 'Safety Pin', emoji: '🧷' },
    { name: 'Broom', emoji: '🧹' },
    { name: 'Basket', emoji: '🧺' },
    { name: 'Roll of Paper', emoji: '🧻' },
    { name: 'Soap', emoji: '🧼' },
    { name: 'Sponge', emoji: '🧽' },
    { name: 'Fire Extinguisher', emoji: '🧯' },
    { name: 'Shopping Cart', emoji: '🛒' },
    { name: 'Cigarette', emoji: '🚬' },
    { name: 'Coffin', emoji: '⚰' },
    { name: 'Funeral Urn', emoji: '⚱' },
    { name: 'Moai', emoji: '🗿' },
    { name: 'Potable Water', emoji: '🚰' }
  ]
}
