export default {
  emojis: [
    { name: 'Heart with Arrow', emoji: '💘' },
    { name: 'Heart with Ribbon', emoji: '💝' },
    { name: 'Sparkling Heart', emoji: '💖' },
    { name: 'Growing Heart', emoji: '💗' },
    { name: 'Beating Heart', emoji: '💓' },
    { name: 'Revolving Hearts', emoji: '💞' },
    { name: 'Two Hearts', emoji: '💕' },
    { name: 'Heart Decoration', emoji: '💟' },
    { name: 'Heart Exclamation', emoji: '❣' },
    { name: 'Broken Heart', emoji: '💔' },
    { name: 'Red Heart', emoji: '❤️' },
    { name: 'Orange Heart', emoji: '🧡' },
    { name: 'Yellow Heart', emoji: '💛' },
    { name: 'Green Heart', emoji: '💚' },
    { name: 'Blue Heart', emoji: '💙' },
    { name: 'Purple Heart', emoji: '💜' },
    { name: 'Brown Heart', emoji: '🤎' },
    { name: 'Black Heart', emoji: '🖤' },
    { name: 'White Heart', emoji: '🤍' },
    { name: 'Hundred Points', emoji: '💯' },
    { name: 'Anger Symbol', emoji: '💢' },
    { name: 'Speech Balloon', emoji: '💬' },
    { name: 'Eye in Speech Bubble', emoji: '👁️‍🗨️' },
    { name: 'Left Speech Bubble', emoji: '🗨' },
    { name: 'Right Anger Bubble', emoji: '🗯' },
    { name: 'Thought Balloon', emoji: '💭' },
    { name: 'Zzz', emoji: '💤' },
    { name: 'White Flower', emoji: '💮' },
    { name: 'Hot Springs', emoji: '♨' },
    { name: 'Barber Pole', emoji: '💈' },
    { name: 'Stop Sign', emoji: '🛑' },
    { name: 'Twelve O’Clock', emoji: '🕛' },
    { name: 'Twelve-Thirty', emoji: '🕧' },
    { name: 'One O’Clock', emoji: '🕐' },
    { name: 'One-Thirty', emoji: '🕜' },
    { name: 'Two O’Clock', emoji: '🕑' },
    { name: 'Two-Thirty', emoji: '🕝' },
    { name: 'Three O’Clock', emoji: '🕒' },
    { name: 'Three-Thirty', emoji: '🕞' },
    { name: 'Four O’Clock', emoji: '🕓' },
    { name: 'Four-Thirty', emoji: '🕟' },
    { name: 'Five O’Clock', emoji: '🕔' },
    { name: 'Five-Thirty', emoji: '🕠' },
    { name: 'Six O’Clock', emoji: '🕕' },
    { name: 'Six-Thirty', emoji: '🕡' },
    { name: 'Seven O’Clock', emoji: '🕖' },
    { name: 'Seven-Thirty', emoji: '🕢' },
    { name: 'Eight O’Clock', emoji: '🕗' },
    { name: 'Eight-Thirty', emoji: '🕣' },
    { name: 'Nine O’Clock', emoji: '🕘' },
    { name: 'Nine-Thirty', emoji: '🕤' },
    { name: 'Ten O’Clock', emoji: '🕙' },
    { name: 'Ten-Thirty', emoji: '🕥' },
    { name: 'Eleven O’Clock', emoji: '🕚' },
    { name: 'Eleven-Thirty', emoji: '🕦' },
    { name: 'Cyclone', emoji: '🌀' },
    { name: 'Spade Suit', emoji: '♠️' },
    { name: 'Heart Suit', emoji: '♥️' },
    { name: 'Diamond Suit', emoji: '♦️' },
    { name: 'Club Suit', emoji: '♣️' },
    { name: 'Joker', emoji: '🃏' },
    { name: 'Mahjong Red Dragon', emoji: '🀄' },
    { name: 'Flower Playing Cards', emoji: '🎴' },
    { name: 'Muted Speaker', emoji: '🔇' },
    { name: 'Speaker Low Volume', emoji: '🔈' },
    { name: 'Speaker Medium Volume', emoji: '🔉' },
    { name: 'Speaker High Volume', emoji: '🔊' },
    { name: 'Loudspeaker', emoji: '📢' },
    { name: 'Megaphone', emoji: '📣' },
    { name: 'Postal Horn', emoji: '📯' },
    { name: 'Bell', emoji: '🔔' },
    { name: 'Bell with Slash', emoji: '🔕' },
    { name: 'Musical Note', emoji: '🎵' },
    { name: 'Musical Notes', emoji: '🎶' },
    { name: 'Chart Increasing with Yen', emoji: '💹' },
    { name: 'ATM Sign', emoji: '🏧' },
    { name: 'Litter in Bin Sign', emoji: '🚮' },
    { name: 'Potable Water', emoji: '🚰' },
    { name: 'Wheelchair Symbol', emoji: '♿' },
    { name: 'Men’s Room', emoji: '🚹' },
    { name: 'Women’s Room', emoji: '🚺' },
    { name: 'Restroom', emoji: '🚻' },
    { name: 'Baby Symbol', emoji: '🚼' },
    { name: 'Water Closet', emoji: '🚾' },
    { name: 'Warning', emoji: '⚠️' },
    { name: 'Children Crossing', emoji: '🚸' },
    { name: 'No Entry', emoji: '⛔' },
    { name: 'Prohibited', emoji: '🚫' },
    { name: 'No Bicycles', emoji: '🚳' },
    { name: 'No Smoking', emoji: '🚭' },
    { name: 'No Littering', emoji: '🚯' },
    { name: 'Non-Potable Water', emoji: '🚱' },
    { name: 'No Pedestrians', emoji: '🚷' },
    { name: 'No Mobile Phones', emoji: '📵' },
    { name: 'No One Under Eighteen', emoji: '🔞' },
    { name: 'Radioactive', emoji: '☢️' },
    { name: 'Biohazard', emoji: '☣️' },
    { name: 'Up Arrow', emoji: '⬆️' },
    { name: 'Up-Right Arrow', emoji: '↗️' },
    { name: 'Right Arrow', emoji: '➡️' },
    { name: 'Down-Right Arrow', emoji: '↘️' },
    { name: 'Down Arrow', emoji: '⬇️' },
    { name: 'Down-Left Arrow', emoji: '↙️' },
    { name: 'Left Arrow', emoji: '⬅️' },
    { name: 'Up-Left Arrow', emoji: '↖️' },
    { name: 'Up-Down Arrow', emoji: '↕️' },
    { name: 'Left-Right Arrow', emoji: '↔️' },
    { name: 'Right Arrow Curving Left', emoji: '↩️' },
    { name: 'Left Arrow Curving Right', emoji: '↪️' },
    { name: 'Right Arrow Curving Up', emoji: '⤴️' },
    { name: 'Right Arrow Curving Down', emoji: '⤵️' },
    { name: 'Clockwise Vertical Arrows', emoji: '🔃' },
    { name: 'Counterclockwise Arrows Button', emoji: '🔄' },
    { name: 'Back Arrow', emoji: '🔙' },
    { name: 'End Arrow', emoji: '🔚' },
    { name: 'On! Arrow', emoji: '🔛' },
    { name: 'Soon Arrow', emoji: '🔜' },
    { name: 'Top Arrow', emoji: '🔝' },
    { name: 'Place of Worship', emoji: '🛐' },
    { name: 'Atom Symbol', emoji: '⚛️' },
    { name: 'Om', emoji: '🕉' },
    { name: 'Star of David', emoji: '✡️' },
    { name: 'Wheel of Dharma', emoji: '☸️' },
    { name: 'Yin Yang', emoji: '☯️' },
    { name: 'Latin Cross', emoji: '✝️' },
    { name: 'Orthodox Cross', emoji: '☦️' },
    { name: 'Star and Crescent', emoji: '☪️' },
    { name: 'Peace Symbol', emoji: '☮️' },
    { name: 'Menorah', emoji: '🕎' },
    { name: 'Dotted Six-Pointed Star', emoji: '🔯' },
    { name: 'Aries', emoji: '♈' },
    { name: 'Taurus', emoji: '♉' },
    { name: 'Gemini', emoji: '♊' },
    { name: 'Cancer', emoji: '♋' },
    { name: 'Leo', emoji: '♌' },
    { name: 'Virgo', emoji: '♍' },
    { name: 'Libra', emoji: '♎' },
    { name: 'Scorpio', emoji: '♏' },
    { name: 'Sagittarius', emoji: '♐' },
    { name: 'Capricorn', emoji: '♑' },
    { name: 'Aquarius', emoji: '♒' },
    { name: 'Pisces', emoji: '♓' },
    { name: 'Ophiuchus', emoji: '⛎' },
    { name: 'Shuffle Tracks Button', emoji: '🔀' },
    { name: 'Repeat Button', emoji: '🔁' },
    { name: 'Repeat Single Button', emoji: '🔂' },
    { name: 'Play Button', emoji: '▶️' },
    { name: 'Fast-Forward Button', emoji: '⏩' },
    { name: 'Next Track Button', emoji: '⏭' },
    { name: 'Play or Pause Button', emoji: '⏯' },
    { name: 'Reverse Button', emoji: '◀' },
    { name: 'Fast Reverse Button', emoji: '⏪' },
    { name: 'Last Track Button', emoji: '⏮' },
    { name: 'Upwards Button', emoji: '🔼' },
    { name: 'Fast Up Button', emoji: '⏫' },
    { name: 'Downwards Button', emoji: '🔽' },
    { name: 'Fast Down Button', emoji: '⏬' },
    { name: 'Pause Button', emoji: '⏸' },
    { name: 'Stop Button', emoji: '⏹' },
    { name: 'Record Button', emoji: '⏺' },
    { name: 'Eject Button', emoji: '⏏️' },
    { name: 'Cinema', emoji: '🎦' },
    { name: 'Dim Button', emoji: '🔅' },
    { name: 'Bright Button', emoji: '🔆' },
    { name: 'Antenna Bars', emoji: '📶' },
    { name: 'Vibration Mode', emoji: '📳' },
    { name: 'Mobile Phone Off', emoji: '📴' },
    { name: 'Female Sign', emoji: '♀️' },
    { name: 'Male Sign', emoji: '♂️' },
    { name: 'Multiply', emoji: '✖️' },
    { name: 'Plus', emoji: '➕' },
    { name: 'Minus', emoji: '➖' },
    { name: 'Divide', emoji: '➗' },
    { name: 'Infinity', emoji: '♾️' },
    { name: 'Double Exclamation Mark', emoji: '‼️' },
    { name: 'Exclamation Question Mark', emoji: '⁉️' },
    { name: 'Question Mark', emoji: '❓' },
    { name: 'White Question Mark', emoji: '❔' },
    { name: 'White Exclamation Mark', emoji: '❕' },
    { name: 'Exclamation Mark', emoji: '❗' },
    { name: 'Wavy Dash', emoji: '〰️' },
    { name: 'Currency Exchange', emoji: '💱' },
    { name: 'Heavy Dollar Sign', emoji: '💲' },
    { name: 'Medical Symbol', emoji: '⚕️' },
    { name: 'Recycling Symbol', emoji: '♻️' },
    { name: 'Fleur-de-lis', emoji: '⚜️' },
    { name: 'Trident Emblem', emoji: '🔱' },
    { name: 'Name Badge', emoji: '📛' },
    { name: 'Japanese Symbol for Beginner', emoji: '🔰' },
    { name: 'Hollow Red Circle', emoji: '⭕' },
    { name: 'Check Mark Button', emoji: '✅' },
    { name: 'Check Box with Check', emoji: '☑️' },
    { name: 'Check Mark', emoji: '✔️' },
    { name: 'Cross Mark', emoji: '❌' },
    { name: 'Cross Mark Button', emoji: '❎' },
    { name: 'Curly Loop', emoji: '➰' },
    { name: 'Double Curly Loop', emoji: '➿' },
    { name: 'Part Alternation Mark', emoji: '〽️' },
    { name: 'Eight-Spoked Asterisk', emoji: '✳️' },
    { name: 'Eight-Pointed Star', emoji: '✴️' },
    { name: 'Sparkle', emoji: '❇️' },
    { name: 'Copyright', emoji: '©️' },
    { name: 'Registered', emoji: '®️' },
    { name: 'Trade Mark', emoji: '™️' },
    { name: 'Keycap Number Sign', emoji: '#️⃣' },
    { name: 'Keycap Asterisk', emoji: '*️⃣' },
    { name: 'Keycap Digit Zero', emoji: '0️⃣' },
    { name: 'Keycap Digit One', emoji: '1️⃣' },
    { name: 'Keycap Digit Two', emoji: '2️⃣' },
    { name: 'Keycap Digit Three', emoji: '3️⃣' },
    { name: 'Keycap Digit Four', emoji: '4️⃣' },
    { name: 'Keycap Digit Five', emoji: '5️⃣' },
    { name: 'Keycap Digit Six', emoji: '6️⃣' },
    { name: 'Keycap Digit Seven', emoji: '7️⃣' },
    { name: 'Keycap Digit Eight', emoji: '8️⃣' },
    { name: 'Keycap Digit Nine', emoji: '9️⃣' },
    { name: 'Keycap: 10', emoji: '🔟' },
    { name: 'Input Latin Uppercase', emoji: '🔠' },
    { name: 'Input Latin Lowercase', emoji: '🔡' },
    { name: 'Input Numbers', emoji: '🔢' },
    { name: 'Input Symbols', emoji: '🔣' },
    { name: 'Input Latin Letters', emoji: '🔤' },
    { name: 'A Button (Blood Type)', emoji: '🅰' },
    { name: 'AB Button (Blood Type)', emoji: '🆎' },
    { name: 'B Button (Blood Type)', emoji: '🅱' },
    { name: 'CL Button', emoji: '🆑' },
    { name: 'Cool Button', emoji: '🆒' },
    { name: 'Free Button', emoji: '🆓' },
    { name: 'Information', emoji: 'ℹ️' },
    { name: 'ID Button', emoji: '🆔' },
    { name: 'Circled M', emoji: 'Ⓜ️' },
    { name: 'New Button', emoji: '🆕' },
    { name: 'NG Button', emoji: '🆖' },
    { name: 'O Button (Blood Type)', emoji: '🅾' },
    { name: 'OK Button', emoji: '🆗' },
    { name: 'P Button', emoji: '🅿' },
    { name: 'SOS Button', emoji: '🆘' },
    { name: 'Up! Button', emoji: '🆙' },
    { name: 'Vs Button', emoji: '🆚' },
    { name: 'Japanese “Here” Button', emoji: '🈁' },
    { name: 'Japanese “Service Charge” Button', emoji: '🈂️' },
    { name: 'Japanese “Monthly Amount” Button', emoji: '🈷️' },
    { name: 'Japanese “Not Free of Charge” Button', emoji: '🈶' },
    { name: 'Japanese “Reserved” Button', emoji: '🈯' },
    { name: 'Japanese “Bargain” Button', emoji: '🉐' },
    { name: 'Japanese “Discount” Button', emoji: '🈹' },
    { name: 'Japanese “Free of Charge” Button', emoji: '🈚' },
    { name: 'Japanese “Prohibited” Button', emoji: '🈲' },
    { name: 'Japanese “Acceptable” Button', emoji: '🉑' },
    { name: 'Japanese “Application” Button', emoji: '🈸' },
    { name: 'Japanese “Passing Grade” Button', emoji: '🈴' },
    { name: 'Japanese “Vacancy” Button', emoji: '🈳' },
    { name: 'Japanese “Congratulations” Button', emoji: '㊗️' },
    { name: 'Japanese “Secret” Button', emoji: '㊙️' },
    { name: 'Japanese “Open for Business” Button', emoji: '🈺' },
    { name: 'Japanese “No Vacancy” Button', emoji: '🈵' },
    { name: 'Red Circle', emoji: '🔴' },
    { name: 'Orange Circle', emoji: '🟠' },
    { name: 'Yellow Circle', emoji: '🟡' },
    { name: 'Green Circle', emoji: '🟢' },
    { name: 'Blue Circle', emoji: '🔵' },
    { name: 'Purple Circle', emoji: '🟣' },
    { name: 'Brown Circle', emoji: '🟤' },
    { name: 'Black Circle', emoji: '⚫' },
    { name: 'White Circle', emoji: '⚪' },
    { name: 'Red Square', emoji: '🟥' },
    { name: 'Orange Square', emoji: '🟧' },
    { name: 'Yellow Square', emoji: '🟨' },
    { name: 'Green Square', emoji: '🟩' },
    { name: 'Blue Square', emoji: '🟦' },
    { name: 'Purple Square', emoji: '🟪' },
    { name: 'Brown Square', emoji: '🟫' },
    { name: 'Black Large Square', emoji: '⬛' },
    { name: 'White Large Square', emoji: '⬜' },
    { name: 'Black Medium Square', emoji: '◼️' },
    { name: 'White Medium Square', emoji: '◻️' },
    { name: 'Black Medium-Small Square', emoji: '◾' },
    { name: 'White Medium-Small Square', emoji: '◽' },
    { name: 'Black Small Square', emoji: '▪️' },
    { name: 'White Small Square', emoji: '▫️' },
    { name: 'Large Orange Diamond', emoji: '🔶' },
    { name: 'Large Blue Diamond', emoji: '🔷' },
    { name: 'Small Orange Diamond', emoji: '🔸' },
    { name: 'Small Blue Diamond', emoji: '🔹' },
    { name: 'Red Triangle Pointed Up', emoji: '🔺' },
    { name: 'Red Triangle Pointed Down', emoji: '🔻' },
    { name: 'Diamond with a Dot', emoji: '💠' },
    { name: 'Radio Button', emoji: '🔘' },
    { name: 'White Square Button', emoji: '🔳' },
    { name: 'Black Square Button', emoji: '🔲' }
  ]
}
