export default {
  emojis: [
    { name: 'Person Rowing Boat', emoji: '🚣' },
    { name: 'Map of Japan', emoji: '🗾' },
    { name: 'Snow-Capped Mountain', emoji: '🏔' },
    { name: 'Mountain', emoji: '⛰' },
    { name: 'Volcano', emoji: '🌋' },
    { name: 'Mount Fuji', emoji: '🗻' },
    { name: 'Camping', emoji: '🏕' },
    { name: 'Beach with Umbrella', emoji: '🏖' },
    { name: 'Desert', emoji: '🏜' },
    { name: 'Desert Island', emoji: '🏝' },
    { name: 'National Park', emoji: '🏞' },
    { name: 'Stadium', emoji: '🏟' },
    { name: 'Classical Building', emoji: '🏛' },
    { name: 'Building Construction', emoji: '🏗' },
    { name: 'Houses', emoji: '🏘' },
    { name: 'Derelict House', emoji: '🏚' },
    { name: 'House', emoji: '🏠' },
    { name: 'House with Garden', emoji: '🏡' },
    { name: 'Office Building', emoji: '🏢' },
    { name: 'Japanese Post Office', emoji: '🏣' },
    { name: 'Post Office', emoji: '🏤' },
    { name: 'Hospital', emoji: '🏥' },
    { name: 'Bank', emoji: '🏦' },
    { name: 'Hotel', emoji: '🏨' },
    { name: 'Love Hotel', emoji: '🏩' },
    { name: 'Convenience Store', emoji: '🏪' },
    { name: 'School', emoji: '🏫' },
    { name: 'Department Store', emoji: '🏬' },
    { name: 'Factory', emoji: '🏭' },
    { name: 'Japanese Castle', emoji: '🏯' },
    { name: 'Castle', emoji: '🏰' },
    { name: 'Wedding', emoji: '💒' },
    { name: 'Tokyo Tower', emoji: '🗼' },
    { name: 'Statue of Liberty', emoji: '🗽' },
    { name: 'Church', emoji: '⛪' },
    { name: 'Mosque', emoji: '🕌' },
    { name: 'Hindu Temple', emoji: '🛕' },
    { name: 'Synagogue', emoji: '🕍' },
    { name: 'Shinto Shrine', emoji: '⛩' },
    { name: 'Kaaba', emoji: '🕋' },
    { name: 'Fountain', emoji: '⛲' },
    { name: 'Tent', emoji: '⛺' },
    { name: 'Foggy', emoji: '🌁' },
    { name: 'Night with Stars', emoji: '🌃' },
    { name: 'Cityscape', emoji: '🏙' },
    { name: 'Sunrise Over Mountains', emoji: '🌄' },
    { name: 'Sunrise', emoji: '🌅' },
    { name: 'Cityscape at Dusk', emoji: '🌆' },
    { name: 'Sunset', emoji: '🌇' },
    { name: 'Bridge at Night', emoji: '🌉' },
    { name: 'Carousel Horse', emoji: '🎠' },
    { name: 'Ferris Wheel', emoji: '🎡' },
    { name: 'Roller Coaster', emoji: '🎢' },
    { name: 'Locomotive', emoji: '🚂' },
    { name: 'Railway Car', emoji: '🚃' },
    { name: 'High-Speed Train', emoji: '🚄' },
    { name: 'Bullet Train', emoji: '🚅' },
    { name: 'Train', emoji: '🚆' },
    { name: 'Metro', emoji: '🚇' },
    { name: 'Light Rail', emoji: '🚈' },
    { name: 'Station', emoji: '🚉' },
    { name: 'Tram', emoji: '🚊' },
    { name: 'Monorail', emoji: '🚝' },
    { name: 'Mountain Railway', emoji: '🚞' },
    { name: 'Tram Car', emoji: '🚋' },
    { name: 'Bus', emoji: '🚌' },
    { name: 'Oncoming Bus', emoji: '🚍' },
    { name: 'Trolleybus', emoji: '🚎' },
    { name: 'Minibus', emoji: '🚐' },
    { name: 'Ambulance', emoji: '🚑' },
    { name: 'Fire Engine', emoji: '🚒' },
    { name: 'Police Car', emoji: '🚓' },
    { name: 'Oncoming Police Car', emoji: '🚔' },
    { name: 'Taxi', emoji: '🚕' },
    { name: 'Oncoming Taxi', emoji: '🚖' },
    { name: 'Automobile', emoji: '🚗' },
    { name: 'Oncoming Automobile', emoji: '🚘' },
    { name: 'Sport Utility Vehicle', emoji: '🚙' },
    { name: 'Delivery Truck', emoji: '🚚' },
    { name: 'Articulated Lorry', emoji: '🚛' },
    { name: 'Tractor', emoji: '🚜' },
    { name: 'Racing Car', emoji: '🏎' },
    { name: 'Motorcycle', emoji: '🏍' },
    { name: 'Motor Scooter', emoji: '🛵' },
    { name: 'Auto Rickshaw', emoji: '🛺' },
    { name: 'Bicycle', emoji: '🚲' },
    { name: 'Kick Scooter', emoji: '🛴' },
    { name: 'Bus Stop', emoji: '🚏' },
    { name: 'Motorway', emoji: '🛣' },
    { name: 'Railway Track', emoji: '🛤' },
    { name: 'Fuel Pump', emoji: '⛽' },
    { name: 'Police Car Light', emoji: '🚨' },
    { name: 'Horizontal Traffic Light', emoji: '🚥' },
    { name: 'Vertical Traffic Light', emoji: '🚦' },
    { name: 'Construction', emoji: '🚧' },
    { name: 'Anchor', emoji: '⚓' },
    { name: 'Sailboat', emoji: '⛵' },
    { name: 'Speedboat', emoji: '🚤' },
    { name: 'Passenger Ship', emoji: '🛳' },
    { name: 'Ferry', emoji: '⛴' },
    { name: 'Motor Boat', emoji: '🛥' },
    { name: 'Ship', emoji: '🚢' },
    { name: 'Airplane', emoji: '✈' },
    { name: 'Small Airplane', emoji: '🛩' },
    { name: 'Airplane Departure', emoji: '🛫' },
    { name: 'Airplane Arrival', emoji: '🛬' },
    { name: 'Parachute', emoji: '🪂' },
    { name: 'Seat', emoji: '💺' },
    { name: 'Helicopter', emoji: '🚁' },
    { name: 'Suspension Railway', emoji: '🚟' },
    { name: 'Mountain Cableway', emoji: '🚠' },
    { name: 'Aerial Tramway', emoji: '🚡' },
    { name: 'Satellite', emoji: '🛰' },
    { name: 'Rocket', emoji: '🚀' },
    { name: 'Flying Saucer', emoji: '🛸' },
    { name: 'Ringed Planet', emoji: '🪐' },
    { name: 'Shooting Star', emoji: '🌠' },
    { name: 'Milky Way', emoji: '🌌' },
    { name: 'Umbrella on Ground', emoji: '⛱' },
    { name: 'Fireworks', emoji: '🎆' },
    { name: 'Sparkler', emoji: '🎇' },
    { name: 'Moon Viewing Ceremony', emoji: '🎑' },
    { name: 'Yen Banknote', emoji: '💴' },
    { name: 'Dollar Banknote', emoji: '💵' },
    { name: 'Euro Banknote', emoji: '💶' },
    { name: 'Pound Banknote', emoji: '💷' },
    { name: 'Moai', emoji: '🗿' },
    { name: 'Passport Control', emoji: '🛂' },
    { name: 'Customs', emoji: '🛃' },
    { name: 'Baggage Claim', emoji: '🛄' },
    { name: 'Left Luggage', emoji: '🛅' }
  ]
}
